# Generated by Django 3.0.5 on 2021-02-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodeuser',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='nodeuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='nodeuser',
            name='username',
        ),
        migrations.AddField(
            model_name='nodeuser',
            name='email',
            field=models.EmailField(default='natugetachew@gmail.com', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodeuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='nodeuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='nodeuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='nodeuser',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
