# Generated by Django 3.0.5 on 2021-05-11 00:54

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210212_2200'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='nodeuser',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='nodeuser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
    ]
