# Generated by Django 3.0.5 on 2020-04-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200420_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
