# Generated by Django 3.0.5 on 2020-04-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_node_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='node',
            name='interview',
            field=models.TextField(),
        ),
    ]
